project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3 part 1"
            href: "Hands-on_Ex/Hands-on_Ex03_part1/Hands-on_Ex03_part1.html"
          - text: "Hands-on Exercise 3 part 2"
            href: "Hands-on_Ex/Hands-on_Ex03_part2/Hands-on_Ex03_part2.html"
          - text: "Hands-on Exercise 4 part 1"
            href: "Hands-on_Ex/Hands-on_Ex04_part1/Hands-on_Ex04_part1.html"
          - text: "Hands-on Exercise 4 part 2"
            href: "Hands-on_Ex/Hands-on_Ex04_part2/Hands-on_Ex04_part2.html"
          - text: "Hands-on Exercise 4 part 3"
            href: "Hands-on_Ex/Hands-on_Ex04_part3/Hands-on_Ex04_part3.html"
          - text: "Hands-on Exercise 4 part 4"
            href: "Hands-on_Ex/Hands-on_Ex04_part4/Hands-on_Ex04_part4.html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
            

      - text: "In-Class Exercise"
        menu:
          - text: "In-Class Exercise 2"
            href: "https://public.tableau.com/app/profile/qiuyan.tai/viz/In-classExercise2Superstorereport/Dashboard1"
          - text: "In-Class Exercise 3"
            href: "https://public.tableau.com/shared/F9XXPM8TG?:display_count=n&:origin=viz_share_link"     
          - text: "In-Class Exercise 4"
            href: "In-class_Ex/In-class_Ex_04/In-class_Ex_04.html"
            
      - text: "Take Home Exercise"
        menu:
          - text: "Take Home Exercise 1"
            href: "TakeHome_Ex/TakeHome_Ex01/TakeHome_Ex01.html"
          - text: "Take Home Exercise 1 - classmate"
            href: "TakeHome_Ex/TakeHome_Ex01_classmate/TakeHome_Ex01_classmate.html"
          - text: "Take Home Exercise 2"
            href: "TakeHome_Ex/TakeHome_Ex02/TakeHome_Ex02.html"
            

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual